In [42]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None

In [16]:
covid_vax_data_raw = pd.read_csv('COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv')
print(covid_vax_data_raw.shape)
covid_vax_data_raw.head()

(23384, 80)

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_Dose1_Recip_5PlusPop_Pct,Series_Complete_5Plus,Series_Complete_5PlusPop_Pct,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus
0,12/09/2021,49,MP,108120,3300,24220,80600,0,208521,255663,...,86.2,37463.0,77.9,86789.0,180427.0,224772.0,4755.0,31646.0,1062.0,0.0
1,12/09/2021,49,MT,1684155,99900,692480,891775,0,157578,183540,...,64.4,562791.0,55.9,1366454.0,135612.0,167142.0,226844.0,284251.0,51312.0,384.0
2,12/09/2021,49,WV,3412435,150500,1318780,1943155,0,190410,219050,...,91.4,1236080.0,72.7,2946585.0,173418.0,200835.0,535256.0,631281.0,69112.0,431.0
3,12/09/2021,49,LA,6763450,300700,2700860,3761890,0,145488,172391,...,60.1,2294222.0,52.8,5360471.0,123305.0,155577.0,915444.0,1211609.0,166169.0,1000.0
4,12/09/2021,49,OH,18773745,893500,7191380,10688865,0,160609,187724,...,62.9,6309224.0,57.4,14933983.0,135785.0,170697.0,2290919.0,3490672.0,522786.0,4847.0

In [135]:
print(covid_vax_data_raw.Location.unique())
drop_states = ['MP', 'AS', 'US', 'RP', 'FM', 'DD2', 'VI', 'GU', 'IH2', 'MH', 'VA2', 'BP2', 'LTC', 'PR']

['MP' 'MT' 'WV' 'LA' 'OH' 'VA' 'AK' 'NM' 'MO' 'CT' 'VT' 'AS' 'US' 'AL'
 'RP' 'NE' 'FM' 'DE' 'PR' 'NH' 'SD' 'CA' 'DD2' 'DC' 'IA' 'ND' 'MD' 'KY'
 'MA' 'WI' 'VI' 'FL' 'IN' 'HI' 'SC' 'MI' 'NC' 'GU' 'TN' 'IH2' 'NJ' 'OR'
 'CO' 'MH' 'ID' 'KS' 'NY' 'ME' 'RI' 'MS' 'NV' 'VA2' 'UT' 'AR' 'WA' 'MN'
 'PA' 'TX' 'IL' 'AZ' 'GA' 'OK' 'BP2' 'WY' 'LTC']

In [136]:
covid_vax_data_filt = covid_vax_data_raw[~covid_vax_data_raw['Location'].isin(drop_states)]
print(covid_vax_data_filt.shape)

(18411, 80)

In [138]:
np.sort(covid_vax_data_filt.Location.unique())

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [23]:
one_date_subset = covid_vax_data_filt[covid_vax_data_filt.Date == '12/09/2021']
print(one_date_subset.shape)
one_date_subset.head()

(52, 80)

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_Dose1_Recip_5PlusPop_Pct,Series_Complete_5Plus,Series_Complete_5PlusPop_Pct,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus
1,12/09/2021,49,MT,1684155,99900,692480,891775,0,157578,183540,...,64.4,562791.0,55.9,1366454.0,135612.0,167142.0,226844.0,284251.0,51312.0,384.0
2,12/09/2021,49,WV,3412435,150500,1318780,1943155,0,190410,219050,...,91.4,1236080.0,72.7,2946585.0,173418.0,200835.0,535256.0,631281.0,69112.0,431.0
3,12/09/2021,49,LA,6763450,300700,2700860,3761890,0,145488,172391,...,60.1,2294222.0,52.8,5360471.0,123305.0,155577.0,915444.0,1211609.0,166169.0,1000.0
4,12/09/2021,49,OH,18773745,893500,7191380,10688865,0,160609,187724,...,62.9,6309224.0,57.4,14933983.0,135785.0,170697.0,2290919.0,3490672.0,522786.0,4847.0
5,12/09/2021,49,VA,16057155,722500,5709900,9624755,0,188122,219751,...,81.5,5659645.0,70.5,13561683.0,168887.0,199964.0,1916102.0,3318315.0,422361.0,2867.0

In [25]:
one_date_slim = one_date_subset[['Location', 'Administered_Dose1_Recip_5PlusPop_Pct']]
one_date_slim.columns = ['state', one_date_subset.Date.iloc[0]]
one_date_slim.sort_values(by='state')

   state  12/09/2021
6     AK        68.6
13    AL        61.0
53    AR        65.4
59    AZ        69.4
21    CA        85.3
42    CO        77.0
9     CT        90.0
23    DC        89.5
17    DE        78.8
31    FL        76.6
60    GA        63.7
33    HI        88.4
24    IA        67.6
44    ID         0.0
58    IL        74.5
32    IN        60.2
45    KS        71.8
27    KY        65.1
3     LA        60.1
28    MA        92.1
26    MD        83.0
47    ME        87.4
35    MI        65.7
55    MN        74.5
8     MO        64.6
49    MS        58.2
1     MT        64.4
36    NC        76.6
25    ND        63.4
15    NE        69.6
19    NH        94.8
40    NJ        85.6
7     NM        82.8
50    NV        71.7
46    NY        84.8
4     OH        62.9
61    OK        68.4
41    OR        76.5
56    PA        87.9
18    PR        89.4
48    RI        89.6
34    SC        64.9
20    SD        73.6
38    TN        61.2
57    TX        69.8
52    UT        71.1
5     VA        81.5
10    VT        91.0
54    WA        78.5
29    WI        70.7
2     WV        91.4
63    WY        58.1

In [ ]:
one_date_slim = one_date_subset[['Location', 'Administered_Dose1_Recip_5PlusPop_Pct']]
one_date_slim.columns = ['state', one_date_subset.Date.iloc[0]]
one_date_slim.sort_values(by='state')

## All dates

In [111]:
dates = list(covid_vax_data_filt.Date.unique())

In [32]:
d1_subset = covid_vax_data_filt[covid_vax_data_filt.Date == dates[0]]
d1_slim = d1_subset[['Location', 'Administered_Dose1_Recip_5PlusPop_Pct']]
d1_slim.columns = ['state', dates[0]]
d1_slim.sort_values(by='state', inplace=True)
d1_slim.head()

<ipython-input-32-68e4dd3e7abf>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d1_slim.sort_values(by='state', inplace=True)

   state  12/09/2021
6     AK        68.6
13    AL        61.0
53    AR        65.4
59    AZ        69.4
21    CA        85.3

In [33]:
d2_subset = covid_vax_data_filt[covid_vax_data_filt.Date == dates[1]]
d2_slim = d2_subset[['Location', 'Administered_Dose1_Recip_5PlusPop_Pct']]
d2_slim.columns = ['state', dates[1]]
d2_slim.sort_values(by='state', inplace=True)
d2_slim.head()

<ipython-input-33-d7d3bf0dca73>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2_slim.sort_values(by='state', inplace=True)

    state  12/08/2021
123    AK        68.5
64     AL        60.9
66     AR        65.3
78     AZ        69.3
107    CA        85.1

In [37]:
d1_slim.merge(d2_slim)

   state  12/09/2021  12/08/2021
0     AK        68.6        68.5
1     AL        61.0        60.9
2     AR        65.4        65.3
3     AZ        69.4        69.3
4     CA        85.3        85.1
5     CO        77.0        76.8
6     CT        90.0        89.8
7     DC        89.5        89.2
8     DE        78.8        78.6
9     FL        76.6        76.6
10    GA        63.7        63.6
11    HI        88.4        88.2
12    IA        67.6        67.5
13    ID         0.0         0.0
14    IL        74.5        74.6
15    IN        60.2        60.1
16    KS        71.8        71.7
17    KY        65.1        65.0
18    LA        60.1        60.0
19    MA        92.1        91.9
20    MD        83.0        82.9
21    ME        87.4        87.2
22    MI        65.7        65.6
23    MN        74.5        74.4
24    MO        64.6        64.5
25    MS        58.2        58.1
26    MT        64.4        64.3
27    NC        76.6        76.4
28    ND        63.4        63.3
29    NE        69.6        69.5
30    NH        94.8        94.4
31    NJ        85.6        85.4
32    NM        82.8        82.6
33    NV        71.7        71.6
34    NY        84.8        84.6
35    OH        62.9        62.8
36    OK        68.4        68.2
37    OR        76.5        76.3
38    PA        87.9        87.9
39    PR        89.4        89.3
40    RI        89.6        89.3
41    SC        64.9        64.7
42    SD        73.6        73.3
43    TN        61.2        61.1
44    TX        69.8        69.6
45    UT        71.1        70.9
46    VA        81.5        81.5
47    VT        91.0        90.9
48    WA        78.5        78.4
49    WI        70.7        70.5
50    WV        91.4        91.4
51    WY        58.1        58.0

In [36]:
pd.concat([d1_slim, d2_slim], axis=0)

    state  12/09/2021  12/08/2021
6      AK        68.6         NaN
13     AL        61.0         NaN
53     AR        65.4         NaN
59     AZ        69.4         NaN
21     CA        85.3         NaN
..    ...         ...         ...
101    VT         NaN        90.9
76     WA         NaN        78.4
79     WI         NaN        70.5
103    WV         NaN        91.4
111    WY         NaN        58.0

[104 rows x 3 columns]

## Functions

In [66]:
def create_date_subset(date, df):
    df_subset = df[df.Date == date]
    df_slim = df_subset[['Location', 'Administered_Dose1_Pop_Pct']]
    df_slim.columns = ['state', date]
    df_slim.sort_values(by='state', inplace=True)
    return(df_slim)

In [67]:
create_date_subset(dates[5], covid_vax_data_filt)

    state  12/04/2021
340    AK        63.4
335    AL        56.9
338    AR        60.8
329    AZ        64.8
322    CA        79.5
348    CO        71.9
328    CT        84.7
324    DC        82.5
323    DE        73.5
372    FL        72.2
369    GA        59.4
336    HI        82.6
347    IA        63.0
358    ID        51.0
341    IL        69.5
367    IN        56.1
376    KS        66.7
357    KY        60.7
363    LA        55.9
379    MA        86.5
362    MD        77.5
361    ME        82.6
371    MI        61.6
370    MN        69.5
321    MO        60.3
331    MS        54.1
360    MT        60.3
380    NC        71.3
334    ND        58.5
350    NE        64.5
344    NH        89.1
351    NJ        79.9
366    NM        77.4
374    NV        66.8
325    NY        79.1
333    OH        58.8
352    OK        63.5
337    OR        71.9
330    PA        82.4
383    PR        85.6
375    RI        84.0
377    SC        60.7
342    SD        67.8
364    TN        57.2
382    TX        64.5
355    UT        65.1
346    VA        76.1
378    VT        86.1
381    WA        73.3
332    WI        66.2
356    WV        69.3
359    WY        54.1

In [128]:
dates = list(covid_vax_data_filt.Date.unique())
dates = [d for d in dates if (('2021' in d) & (d >= '02/13/2021'))]
dates.sort()

In [133]:
n = len(dates)
df = create_date_subset(dates[n-1], covid_vax_data_filt)
for date in dates[1:]:
    d_slice = create_date_subset(date, covid_vax_data_filt)
    df = df.merge(d_slice)

In [130]:
df

,state,12/09/2021,12/08/2021,12/07/2021,12/06/2021,12/05/2021,12/04/2021,12/03/2021,12/02/2021,12/01/2021,...,02/22/2021,02/21/2021,02/20/2021,02/19/2021,02/18/2021,02/17/2021,02/16/2021,02/15/2021,02/14/2021,02/13/2021
0,AK,63.8,63.7,63.6,63.6,63.4,63.4,63.2,63.1,62.9,...,21.0,20.9,20.3,19.7,18.3,17.9,17.7,17.6,17.3,16.7
1,AL,57.3,57.3,57.2,57.1,57.1,56.9,56.9,56.7,56.6,...,11.9,11.8,11.7,11.4,10.5,10.3,10.1,9.9,9.9,9.7
2,AR,61.4,61.3,61.1,61.1,61.0,60.8,60.8,60.7,60.6,...,12.3,12.2,12.1,12.0,11.5,11.5,11.4,11.3,11.2,10.9
3,AZ,65.4,65.2,65.1,65.1,65.0,64.8,64.7,64.6,64.4,...,14.9,14.6,14.3,13.9,12.2,11.9,11.8,11.6,11.2,10.8
4,CA,80.1,80.0,79.8,79.8,79.6,79.5,79.3,79.1,78.9,...,13.9,13.7,13.4,13.0,12.3,12.0,11.9,11.7,11.4,11.0
5,CO,72.5,72.4,72.3,72.2,72.1,71.9,71.9,71.7,71.6,...,14.4,14.2,13.9,13.6,12.6,12.2,11.9,11.6,10.9,10.6
6,CT,85.5,85.3,85.1,85.0,85.0,84.7,84.5,84.4,84.2,...,16.6,16.2,16.0,15.6,14.6,14.2,13.8,13.5,13.2,12.9
7,DC,83.7,83.5,83.2,83.0,82.7,82.5,82.1,81.9,81.8,...,10.1,10.1,9.9,9.8,8.8,8.7,8.6,8.5,8.2,7.9
8,DE,74.4,74.2,73.5,73.5,73.5,73.5,73.4,73.3,73.1,...,13.6,13.4,13.4,13.1,12.2,11.9,11.8,11.7,11.5,11.2
9,FL,72.5,72.5,72.5,72.5,72.4,72.2,72.1,72.0,71.9,...,13.1,13.1,12.8,12.8,11.7,11.4,11.2,11.0,10.8,10.5
10,GA,59.8,59.7,59.6,59.4,59.4,59.4,59.3,59.2,59.1,...,11.2,11.1,10.9,10.7,9.9,9.6,9.6,9.6,9.5,9.2
11,HI,83.1,83.0,82.9,82.8,82.8,82.6,82.5,82.4,82.1,...,15.9,15.6,15.3,15.0,12.4,12.2,12.0,11.9,11.6,11.4
12,IA,63.4,63.3,63.2,63.0,63.0,63.0,62.9,62.8,62.7,...,14.5,14.3,13.8,13.2,12.0,11.7,11.5,11.2,10.7,10.1
13,ID,51.3,51.2,51.2,51.1,51.1,51.0,50.9,50.9,50.8,...,12.9,12.6,12.3,12.0,11.1,10.9,10.7,10.6,9.9,9.4
14,IL,70.1,70.2,70.0,69.9,69.7,69.5,69.3,69.1,69.6,...,13.9,13.9,13.5,13.1,12.4,12.2,11.9,11.7,11.3,10.9
15,IN,56.5,56.4,56.3,56.3,56.2,56.1,56.0,55.9,55.7,...,13.1,13.0,12.8,12.5,11.9,11.8,11.7,11.6,11.4,11.1
16,KS,67.2,67.1,67.0,66.9,66.8,66.7,66.5,66.5,66.3,...,13.0,12.9,12.5,12.1,11.0,10.8,10.6,10.5,10.4,9.9
17,KY,61.1,61.0,60.9,60.9,60.8,60.7,60.5,60.5,60.3,...,13.3,13.2,12.9,12.7,12.0,11.9,11.8,11.6,11.3,11.0
18,LA,56.2,56.1,56.1,56.0,56.0,55.9,55.8,55.8,55.7,...,12.6,12.5,12.3,12.1,11.3,11.3,11.2,11.1,11.0,10.6
19,MA,87.3,87.1,87.0,86.9,86.7,86.5,86.3,86.1,85.9,...,15.5,15.2,14.8,14.2,13.1,12.6,12.4,12.2,11.8,11.1
20,MD,78.1,77.9,77.8,77.7,77.6,77.5,77.3,77.2,77.1,...,12.9,12.7,12.6,12.2,11.3,11.0,10.9,10.8,10.5,10.2
21,ME,83.2,83.1,83.0,82.8,82.7,82.6,82.4,82.3,82.1,...,15.4,14.4,14.4,14.4,13.2,13.2,13.0,12.9,10.7,10.7
22,MI,62.0,61.9,61.8,61.8,61.8,61.6,61.5,61.4,61.3,...,13.1,12.9,12.7,12.5,11.8,11.6,11.5,11.4,11.2,10.8
23,MN,69.9,69.8,69.7,69.7,69.6,69.5,69.3,69.2,69.1,...,14.1,14.1,13.8,13.5,12.4,12.1,11.9,11.7,11.4,11.1
24,MO,60.8,60.6,60.5,60.5,60.4,60.3,60.1,60.0,59.8,...,11.7,11.6,11.4,11.1,10.2,10.0,9.9,9.8,9.7,9.3
25,MS,54.7,54.5,54.5,54.1,54.1,54.1,54.1,54.1,54.0,...,12.0,11.9,11.7,11.6,10.8,10.8,10.8,10.7,10.6,10.3
26,MT,60.7,60.6,60.5,60.3,60.3,60.3,60.1,60.0,59.9,...,15.8,15.6,15.2,14.8,12.8,12.5,12.3,12.2,12.0,11.5
27,NC,72.2,72.0,71.8,71.5,71.4,71.3,70.8,70.6,70.4,...,13.1,12.9,12.7,12.6,11.6,11.5,11.3,11.2,11.0,10.5
28,ND,58.9,58.8,58.7,58.5,58.5,58.5,58.4,58.2,58.1,...,16.4,16.2,15.9,15.6,13.6,13.3,13.3,13.3,13.0,12.6
29,NE,64.9,64.8,64.8,64.5,64.5,64.5,64.3,64.3,64.1,...,13.3,13.0,12.6,12.1,10.7,10.4,10.3,10.2,10.1,9.8
30,NH,90.4,90.1,89.8,89.6,89.3,89.1,88.5,88.2,87.9,...,14.1,13.7,13.2,12.7,11.9,11.5,11.4,11.2,11.1,10.6
31,NJ,80.6,80.4,80.3,80.1,80.0,79.9,79.7,79.4,79.3,...,13.9,13.8,13.6,13.4,12.9,12.5,12.1,11.9,11.6,11.4
32,NM,78.0,77.9,77.7,77.7,77.5,77.4,77.2,76.9,76.7,...,19.5,19.3,18.9,18.5,15.0,14.8,14.7,14.3,14.0,13.5
33,NV,67.4,67.2,67.2,67.1,67.0,66.8,66.7,66.6,66.5,...,13.0,12.9,12.7,12.2,11.2,11.0,10.8,10.8,10.5,10.3
34,NY,79.9,79.7,79.5,79.4,79.3,79.1,78.8,78.6,78.4,...,12.3,12.1,12.0,11.8,11.1,10.9,10.8,10.5,10.3,10.0
35,OH,59.2,59.1,59.0,58.9,58.9,58.8,58.7,58.6,58.5,...,12.8,12.7,12.5,12.2,11.5,11.3,11.2,11.0,10.6,10.3
36,OK,64.0,63.8,63.7,63.6,63.5,63.5,63.2,63.1,62.9,...,14.9,14.7,14.4,14.2,12.3,12.3,12.2,12.2,12.1,11.8
37,OR,72.3,72.2,72.1,72.1,72.0,71.9,71.8,71.6,71.5,...,13.2,13.0,12.8,12.5,11.7,11.5,11.4,11.3,11.2,11.0
38,PA,83.1,83.1,82.9,82.8,82.5,82.4,82.2,82.0,81.8,...,13.3,13.0,12.7,12.5,11.6,11.3,10.7,10.7,10.7,10.0
39,PR,86.2,86.0,85.8,85.8,85.6,85.6,85.3,85.2,84.9,...,10.1,10.1,9.9,9.7,8.9,8.7,8.6,8.5,8.5,8.3
40,RI,85.0,84.7,84.6,84.3,84.1,84.0,83.7,83.6,83.4,...,13.6,13.0,12.5,11.9,10.4,9.9,9.6,9.5,9.3,9.1
41,SC,61.2,61.1,61.0,60.9,60.8,60.7,60.6,60.5,60.3,...,12.8,12.6,12.4,12.1,11.1,10.9,10.7,10.6,10.4,10.1
42,SD,68.5,68.3,68.2,67.9,67.9,67.8,67.6,67.3,67.2,...,17.9,17.7,17.3,16.8,13.4,13.0,12.7,12.7,12.6,12.2
43,TN,57.5,57.5,57.4,57.2,57.2,57.2,57.1,57.0,56.9,...,11.1,11.0,10.9,10.7,10.1,9.9,9.9,9.8,9.6,9.3
44,TX,65.0,64.9,64.8,64.7,64.6,64.5,64.4,64.3,64.2,...,11.4,11.3,11.2,11.1,0.0,0.0,0.0,0.0,0.0,0.0
45,UT,65.6,65.5,65.3,65.1,65.1,65.1,65.0,64.9,64.9,...,11.1,11.1,11.1,10.7,10.1,9.8,9.8,9.6,9.6,9.6
46,VA,76.7,76.7,76.5,76.4,76.3,76.1,76.0,75.8,75.7,...,14.0,13.8,13.7,13.6,12.6,12.4,12.3,12.1,11.8,11.6
47,VT,86.7,86.6,86.6,86.5,86.3,86.1,85.8,85.7,85.5,...,14.8,14.4,13.9,13.6,12.7,12.6,12.5,12.0,11.7,11.3
48,WA,73.8,73.7,73.6,73.4,73.4,73.3,73.2,73.1,73.0,...,13.5,13.4,13.2,12.9,12.1,11.9,11.7,11.6,11.5,11.1
49,WI,66.7,66.5,66.4,66.4,66.4,66.2,66.1,66.0,65.9,...,14.9,14.8,14.5,14.1,13.1,12.9,12.7,12.5,12.2,11.8
50,WV,86.7,86.7,69.4,69.3,69.3,69.3,69.0,69.0,53.9,...,16.0,15.9,15.8,15.3,14.2,14.1,14.0,13.9,13.8,13.5
51,WY,54.6,54.5,54.4,54.2,54.2,54.1,54.0,53.9,53.8,...,15.7,15.3,15.2,14.9,13.0,12.5,12.5,12.5,12.4,11.4

In [139]:
df.to_excel('covid_by_state_flourish.xlsx', index=False)