In [1]:
import numpy as np
import pandas as pd

In [61]:
county_results = pd.read_csv('president_county_candidate.csv')
county_results.head(10)

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True
5  Delaware  New Castle County   Donald Trump   REP        88364  False
6  Delaware  New Castle County   Jo Jorgensen   LIB         2953  False
7  Delaware  New Castle County  Howie Hawkins   GRN         1282  False
8  Delaware      Sussex County   Donald Trump   REP        71230   True
9  Delaware      Sussex County      Joe Biden   DEM        56682  False

In [62]:
county_results_2p = county_results[county_results['candidate'].isin(['Joe Biden', 'Donald Trump'])]
state_results = county_results_2p.groupby(['state', 'candidate']).sum().reset_index()
state_results

             state     candidate  total_votes  won
0          Alabama  Donald Trump      1441168   54
1          Alabama     Joe Biden       849648   13
2           Alaska  Donald Trump       189892   20
3           Alaska     Joe Biden       153405   17
4          Arizona  Donald Trump      1661686   10
..             ...           ...          ...  ...
97   West Virginia     Joe Biden       235984    0
98       Wisconsin  Donald Trump      1610065   58
99       Wisconsin     Joe Biden      1630673   14
100        Wyoming  Donald Trump       193559   21
101        Wyoming     Joe Biden        73491    2

[102 rows x 4 columns]

In [63]:
two_rows = state_results[state_results.state == 'Alabama']
two_rows[two_rows.candidate == 'Joe Biden'].total_votes

1    849648
Name: total_votes, dtype: int64

In [64]:
def get_biden_proportion(two_rows):
    return(two_rows[two_rows.candidate == 'Joe Biden'].total_votes * 1.0 / sum(two_rows.total_votes))

In [65]:
get_biden_proportion(two_rows)

1    0.370893
Name: total_votes, dtype: float64

In [66]:
biden_prop = state_results.groupby('state').apply(get_biden_proportion).reset_index()
biden_prop.drop(['level_1'], axis=1, inplace=True)
biden_prop['state_abbr'] = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
biden_prop['biden_margin'] = [(prop - .5) * 2 for prop in biden_prop.total_votes]
biden_prop.columns = ['state', 'biden_pct', 'state_abbr', 'biden_margin']

In [67]:
biden_prop

                   state  biden_pct state_abbr  biden_margin
0                Alabama   0.370893         AL     -0.258214
1                 Alaska   0.446858         AK     -0.106284
2                Arizona   0.501568         AZ      0.003137
3               Arkansas   0.357876         AR     -0.284249
4             California   0.649097         CA      0.298194
5               Colorado   0.569383         CO      0.138766
6            Connecticut   0.601725         CT      0.203449
7               Delaware   0.596267         DE      0.192535
8   District of Columbia   0.944670         DC      0.889339
9                Florida   0.483052         FL     -0.033895
10               Georgia   0.501193         GA      0.002387
11                Hawaii   0.650327         HI      0.300653
12                 Idaho   0.341229         ID     -0.317543
13              Illinois   0.600976         IL      0.201952
14               Indiana   0.418018         IN     -0.163964
15                  Iowa   0.458167         IA     -0.083665
16                Kansas   0.424273         KS     -0.151455
17              Kentucky   0.367999         KY     -0.264002
18             Louisiana   0.405356         LA     -0.189289
19                 Maine   0.544646         ME      0.089292
20              Maryland   0.670290         MD      0.340581
21         Massachusetts   0.671155         MA      0.342311
22              Michigan   0.514136         MI      0.028271
23             Minnesota   0.536395         MN      0.072790
24           Mississippi   0.416150         MS     -0.167700
25              Missouri   0.421642         MO     -0.156716
26               Montana   0.416028         MT     -0.167944
27              Nebraska   0.402159         NE     -0.195681
28                Nevada   0.512231         NV      0.024462
29         New Hampshire   0.537483         NH      0.074967
30            New Jersey   0.580713         NJ      0.161426
31            New Mexico   0.555185         NM      0.110370
32              New York   0.617361         NY      0.234721
33        North Carolina   0.493158         NC     -0.013684
34          North Dakota   0.327826         ND     -0.344348
35                  Ohio   0.459233         OH     -0.081534
36              Oklahoma   0.330600         OK     -0.338801
37                Oregon   0.583072         OR      0.166143
38          Pennsylvania   0.505971         PA      0.011942
39          Rhode Island   0.605102         RI      0.210204
40        South Carolina   0.440734         SC     -0.118532
41          South Dakota   0.365652         SD     -0.268696
42             Tennessee   0.381704         TN     -0.236593
43                 Texas   0.471693         TX     -0.056614
44                  Utah   0.393064         UT     -0.213872
45               Vermont   0.682992         VT      0.365984
46              Virginia   0.551547         VA      0.103094
47            Washington   0.599255         WA      0.198510
48         West Virginia   0.302015         WV     -0.395971
49             Wisconsin   0.503180         WI      0.006359
50               Wyoming   0.275196         WY     -0.449609

In [68]:
biden_prop.to_excel('biden_prop.xlsx')